CREATE DATABASE demo_db;


CREATE TABLE IF NOT EXISTS clients
( id INTEGER NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone VARCHAR(56) NOT NULL,
  img VARCHAR(255) NOR NULL,
  PRIMARY KEY (id)
);


